// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag at
// 2019-08-30 16:28:00.910425 +0800 CST m=+0.075843003

package docs

import (
	"bytes"
	"encoding/json"
	"strings"

	"github.com/alecthomas/template"
	"github.com/swaggo/swag"
)

var doc = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{.Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://git.vs9.cn",
        "contact": {
            "name": "jif",
            "url": "http://www.swagger.io/support",
            "email": "35802713@qq.com"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/demo/index": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "演示",
                "parameters": [
                    {
                        "description": "参数对象,注意,此参数应该被包含在通用参数的data属性内",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/controllers.DemoController"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":0000,\"data\":{},\"message\":\"\",\"success\":true}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "controllers.Demo": {
            "type": "object",
            "properties": {
                "id": {
                    "description": "编号",
                    "type": "integer",
                    "example": 1
                },
                "name": {
                    "description": "名称",
                    "type": "string",
                    "example": "jif"
                }
            }
        },
        "controllers.DemoController": {
            "type": "object",
            "properties": {
                "clientType": {
                    "description": "客户端类型 1安卓,2IOS,3WAP,4PC,5微信小程序 6支付宝小程序 7 百度小程序 8 安卓联盟的快应用 9 待定",
                    "type": "integer"
                },
                "data": {
                    "description": "业务数据",
                    "type": "object",
                    "$ref": "#/definitions/controllers.Demo"
                },
                "sign": {
                    "description": "签名,特殊算法后的签名,用于接口非法调用判定",
                    "type": "string"
                },
                "timestamp": {
                    "description": "当前时间戳",
                    "type": "string"
                },
                "token": {
                    "type": "string",
                    "example": "e10adc3949ba59abbe56e057f20f883e"
                }
            }
        }
    }
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = swaggerInfo{
	Version:     "1.0b125",
	Host:        "",
	BasePath:    "/",
	Schemes:     []string{},
	Title:       "Gin API123",
	Description: "Golang API 演示, 主要是促成代码生成和数据库以及缓存使用,编写简单易于开发业务的框架 <br>技术栈:GOLang 1.12 ,  GIN , XORM , mysql , redis",
}

type s struct{}

func (s *s) ReadDoc() string {
	sInfo := SwaggerInfo
	sInfo.Description = strings.Replace(sInfo.Description, "\n", "\\n", -1)

	t, err := template.New("swagger_info").Funcs(template.FuncMap{
		"marshal": func(v interface{}) string {
			a, _ := json.Marshal(v)
			return string(a)
		},
	}).Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, sInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register(swag.Name, &s{})
}
